### ISSUE TITLE
Package kompiliert nicht

### ISSUE THREAD

**Issue by fairlight1337** [owinklerhb/camera_topic_uwsim#1]
Ich habe die Dependencies noch leicht angepasst, damit `sensor_msgs` mitsamt `catkin` eingelinkt wird. Kannst Du das nochmal ausprobieren?

Ansonsten installiere doch mal OpenCV aus den debs:

``` bash
$ sudo apt-get install libopencv-core2.4 libopencv-highgui2.4 libopencv-imgproc2.4
```

Auf welcher Ubuntu-Version bist du?

``` bash
$ cat /etc/issue
```

**Comment by owinklerhb** [comment]
Ubuntu 14.04.4 LTS \n \l
Habe OpenCV nach dieser Anleitung installiert:
http://rodrigoberriel.com/2014/10/installing-opencv-3-0-0-on-ubuntu-14-04/

**Comment by fairlight1337** [comment]
Und hat sich was getan?

**Comment by owinklerhb** [comment]
ich kann zumindest opencv in den sest smaples zum laufen gebracht. catkin_ws lässt sich aber noch nicht kompilieren.

make[1]: **\* [camera_topic_uwsim/CMakeFiles/camera_topic_uwsim.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
[ 72%] Built target mar_action
[ 72%] Built target mar_robot
[ 73%] [ 73%] Built target republish
Built target polled_camera_gencpp
[ 73%] [ 73%] Built target list_transports
[ 74%] Built target camera_info_manager
Built target image_transport_plugins
make: **\* [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by fairlight1337** [comment]
Hier noch der Ort, an dem dann die CV-Verarbeitung geschehen muss: [CTUWSim.cpp](https://github.com/owinklerhb/camera_topic_uwsim/blob/master/src/CTUWSim.cpp#L34)

Dort kannst Du dann das Bild verarbeiten und die Daten in eine Datei schreiben.

**Comment by fairlight1337** [comment]
Kannst Du etwas mehr vom build-log posten? Der tatsächliche Fehler ist leider nicht sichtbar.

**Comment by fairlight1337** [comment]
Um nicht alle Pakete sondern nur Deins zu bauen, kannst Du auch

``` bash
$ catkin_make --pkg camera_topic_uwsim
```

benutzen.

**Comment by owinklerhb** [comment]
wo genau finde ich den build log?

**Comment by fairlight1337** [comment]
Der Output in der Konsole, den Du eben schonmal gepostet hast. Da, wo steht, dass das Kompilieren fehl schlägt. Poste einfach ein wenig mehr davon, dann kann ich besser absehen, was derzeit noch die Probleme verursacht.

**Comment by owinklerhb** [comment]
olaf@olaf-W230SS:~/catkin_ws$ catkin_make
Base path: /home/olaf/catkin_ws
Source space: /home/olaf/catkin_ws/src
Build space: /home/olaf/catkin_ws/build
Devel space: /home/olaf/catkin_ws/devel
Install space: /home/olaf/catkin_ws/install
####

#### Running command: "make cmake_check_build_system" in "/home/olaf/catkin_ws/build"

####
####

#### Running command: "make -j8 -l8" in "/home/olaf/catkin_ws/build"

####
[  0%] Built target arm5_init
[  0%] Built target _arm5_controller_generate_messages_check_deps_SendMessage
[  0%] [  0%] [  0%] Built target _arm5_controller_generate_messages_check_deps_setOneZero
Built target _arm5_controller_generate_messages_check_deps_setZero
Built target _arm5_controller_generate_messages_check_deps_ReadMessage
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target _arm5_controller_generate_messages_check_deps_setPID
[  0%] Built target _arm5_controller_generate_messages_check_deps_setParams
[  0%] [  0%] Built target std_msgs_generate_messages_lisp
Built target _mar_msgs_generate_messages_check_deps_TemplateTrack
[  0%] [  0%] Built target std_msgs_generate_messages_py
Built target sensor_msgs_generate_messages_cpp
[  0%] Built target roscpp_generate_messages_py
[  0%] [  0%] Built target roscpp_generate_messages_lisp
Built target rosgraph_msgs_generate_messages_py
[  0%] [  0%] [  0%] [  0%] Built target _arm5_power_control_generate_messages_check_deps_onOff
Built target sensor_msgs_generate_messages_py
Built target rosgraph_msgs_generate_messages_lisp
Built target geometry_msgs_generate_messages_cpp
[  0%] [  0%] Built target roscpp_generate_messages_cpp
Built target sensor_msgs_generate_messages_lisp
[  0%] [  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_py
Built target rosgraph_msgs_generate_messages_cpp
[  0%] Linking CXX executable /home/olaf/catkin_ws/devel/lib/camera_topic_uwsim/camera_topic_uwsim
Built target gtest
[  0%] Built target teleop_twist_joy
[  0%] [  0%] [  0%] Built target _laser_assembler_generate_messages_check_deps_AssembleScans2
Built target _underwater_sensor_msgs_generate_messages_check_deps_Pressure
Built target _polled_camera_generate_messages_check_deps_GetPolledImage
[  2%] Built target mar_ros_bridge
[  2%] Built target _laser_assembler_generate_messages_check_deps_AssembleScans
[  4%] Built target visp_bridge
[  4%] Built target _underwater_sensor_msgs_generate_messages_check_deps_DVL
[  4%] Built target _visp_camera_calibration_generate_messages_check_deps_ImageAndPoints
[  4%] [  4%] Built target _visp_camera_calibration_generate_messages_check_deps_calibrate
Built target _visp_camera_calibration_generate_messages_check_deps_ImagePoint
[  4%] Built target image_proc_gencfg
[  4%] [  4%] Built target _visp_camera_calibration_generate_messages_check_deps_CalibPoint
Built target _visp_camera_calibration_generate_messages_check_deps_CalibPointArray
[  4%] Built target _visp_hand2eye_calibration_generate_messages_check_deps_compute_effector_camera
[  4%] [  4%] Built target _visp_hand2eye_calibration_generate_messages_check_deps_TransformArray
Built target _visp_hand2eye_calibration_generate_messages_check_deps_compute_effector_camera_quick
[  4%] Built target _visp_hand2eye_calibration_generate_messages_check_deps_reset
[  4%] Built target _visp_tracker_generate_messages_check_deps_KltSettings
[  4%] Built target _visp_tracker_generate_messages_check_deps_MovingEdgeSettings
[  4%] [  4%] Built target _visp_tracker_generate_messages_check_deps_MovingEdgeSites
Built target _visp_tracker_generate_messages_check_deps_KltPoints
[  4%] Built target _visp_tracker_generate_messages_check_deps_MovingEdgeSite
[  5%] Built target visp_tracker_gencfg
[  5%] Built target _visp_tracker_generate_messages_check_deps_KltPoint
[  5%] Built target _visp_tracker_generate_messages_check_deps_TrackerSettings
[  6%] Built target mar_msgs_generate_messages_py
[  6%] [  7%] Built target mar_msgs_generate_messages_cpp
Built target visp_tracker_viewer
[  7%] [  8%] Built target _visp_tracker_generate_messages_check_deps_Init
Built target mar_msgs_generate_messages_lisp
[ 11%] [ 14%] [ 18%] [ 19%] Built target arm5_controller_generate_messages_cpp
Built target arm5_controller_generate_messages_lisp
Built target arm5_controller_generate_messages_py
Built target arm5_power_control_generate_messages_cpp
[ 20%] Built target arm5_power_control_generate_messages_py
[ 21%] [ 23%] [ 23%] Checking md5sum on /home/olaf/catkin_ws/devel/share/visp_tracker/bag/tutorial-static-box.bag
Built target camera_calibration_parsers
Built target mar_core
[ 23%] Built target arm5_power_control_generate_messages_lisp
[ 27%] Built target polled_camera_generate_messages_cpp
[ 27%] Built target image_transport
Built target visp_tracker_bag
[ 28%] [ 31%] [ 31%] Built target laser_assembler_generate_messages_cpp
Built target laser_assembler_generate_messages_py
Built target polled_camera_generate_messages_lisp
[ 32%] Built target teleop_twist_joy_node
[ 33%] Built target polled_camera_generate_messages_py
[ 34%] Built target laser_assembler_generate_messages_lisp
[ 35%] Built target underwater_sensor_msgs_generate_messages_py
[ 35%] [ 36%] [ 37%] Built target test_odom_pub
Built target underwater_sensor_msgs_generate_messages_cpp
[ 38%] Built target test_odom_sub
Built target underwater_sensor_msgs_generate_messages_lisp
[ 40%] Built target visp_camera_calibration_generate_messages_cpp
[ 41%] Built target visp_camera_calibration_common
[ 44%] [ 44%] Built target visp_camera_calibration_generate_messages_lisp
Built target visp_bridge_convert_camera_parameters
[ 47%] [ 49%] Built target visp_camera_calibration_generate_messages_py
[ 51%] Built target visp_hand2eye_calibration_generate_messages_cpp
Built target visp_hand2eye_calibration_generate_messages_lisp
[ 52%] Built target visp_hand2eye_calibration_common
[ 55%] Built target visp_hand2eye_calibration_generate_messages_py
[ 59%] Built target visp_tracker_generate_messages_lisp
[ 64%] [ 64%] Built target visp_tracker_generate_messages_py
Built target mar_msgs_generate_messages
[ 68%] Built target visp_tracker_generate_messages_cpp
[ 68%] Built target arm5_controller_generate_messages
[ 69%] [ 69%] [ 70%] Built target powerClient
Built target arm5_power_control_generate_messages
Built target arm5_control
[ 70%] [ 71%] [ 71%] Built target powerServer
Built target camera_calibration_parsers_wrapper
Built target convert
CMakeFiles/camera_topic_uwsim.dir/src/main.cpp.o: In function `cv::String::~String()':
main.cpp:(.text._ZN2cv6StringD2Ev[_ZN2cv6StringD5Ev]+0x14): undefined reference to`cv::String::deallocate()'
CMakeFiles/camera_topic_uwsim.dir/src/main.cpp.o: In function `cv::String::operator=(cv::String const&)':
main.cpp:(.text._ZN2cv6StringaSERKS0_[_ZN2cv6StringaSERKS0_]+0x28): undefined reference to `cv::String::deallocate()'
collect2: error: ld returned 1 exit status
make[2]: **\* [/home/olaf/catkin_ws/devel/lib/camera_topic_uwsim/camera_topic_uwsim] Error 1
make[1]: **\* [camera_topic_uwsim/CMakeFiles/camera_topic_uwsim.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
[ 72%] Built target mar_action
[ 72%] Built target mar_robot
[ 73%] [ 73%] Built target republish
Built target polled_camera_gencpp
[ 73%] [ 73%] Built target list_transports
[ 74%] Built target camera_info_manager
Built target image_transport_plugins
make: **\* [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by owinklerhb** [comment]
okay, der errorcode ändert sich und er läuft auf verschiedene fehler. mom ich schreibe dir eben die verschiedenen fehler raus

**Comment by owinklerhb** [comment]
make[1]: **\* Waiting for unfinished jobs....
Built target arm5_power_control_generate_messages
Built target arm5_control
[ 70%] Built target powerClient
[ 70%] Built target powerServer
[ 70%] [ 71%] Built target convert
Built target camera_calibration_parsers_wrapper

## make: **\* [all] Error 2

make[1]: **\* Waiting for unfinished jobs....
[ 68%] [ 68%] Built target visp_tracker_generate_messages_cpp
[ 68%] [ 68%] Built target visp_tracker_generate_messages_py
Built target mar_msgs_generate_messages
Built target arm5_controller_generate_messages
[ 68%] Built target arm5_power_control_generate_messages
[ 69%] Built target arm5_control

## make: **\* [all] Error 2

make[1]: **\* Waiting for unfinished jobs....
Built target visp_camera_calibration_generate_messages_py
Built target visp_hand2eye_calibration_common
[ 54%] [ 55%] Built target visp_tracker_generate_messages_lisp
Built target visp_hand2eye_calibration_generate_messages_cpp
[ 59%] [ 60%] Built target visp_hand2eye_calibration_generate_messages_py
Built target visp_hand2eye_calibration_generate_messages_lisp

## make: **\* [all] Error 2

make[1]: **\* Waiting for unfinished jobs....
Built target visp_hand2eye_calibration_generate_messages_cpp
[ 53%] Built target visp_hand2eye_calibration_generate_messages_py
[ 57%] [ 57%] Built target visp_tracker_generate_messages_cpp
[ 62%] Built target mar_msgs_generate_messages
Built target visp_tracker_generate_messages_py
[ 64%] [ 68%] Built target visp_hand2eye_calibration_generate_messages_lisp
Built target visp_tracker_generate_messages_lisp

## make: **\* [all] Error 2

**Comment by fairlight1337** [comment]
Die beiden hier scheinen ähnliche Probleme zu haben:
- http://answers.ros.org/question/219640/reference-errors-after-opencv3-installation/
- http://stackoverflow.com/questions/25876684/opencv-3-0-undefined-reference-error

**Comment by fairlight1337** [comment]
Komm doch mal vorbei, wenn Du da bist. Dann schauen wir uns das zusammen an.

**Comment by fairlight1337** [comment]
Geloest in 33d74163db22777bbca5ae36af32a228bfdbf967.
